base_images:
  base:
    name: "4.18"
    namespace: ocp
    tag: base
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: konflux-nightly
      version: "4.18"
  latest:
    candidate:
      product: ocp
      stream: konflux-nightly
      version: "4.18"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn-serial
  cron: '@yearly'
  steps:
    cluster_profile: aws-2
    env:
      BASE_DOMAIN: aws-2.ci.openshift.org
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn-serial
  timeout: 5h0m0s
- as: e2e-gcp-ovn-serial
  cron: '@yearly'
  steps:
    cluster_profile: gcp-3
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-ovn-serial
- as: e2e-azure-csi
  cron: '@yearly'
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      ENABLE_LONG_CSI_CERTIFICATION_TESTS: "true"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-csi
- as: fips-payload-scan
  cron: '@yearly'
  steps:
    cluster_profile: aws
    env:
      FIPS_ENABLED: "true"
      MAJOR_MINOR: "4.18"
    test:
    - ref: fips-check-node-scan
    - ref: fips-check-art-fips
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: konflux-nightly-4.18
