kind: Namespace
apiVersion: v1
metadata:
  name: ci-search

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: release-controller-ocp
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: release-controller-ocp-redirect

---
apiVersion: v1
data:
  default.conf: "server {\n  listen 8080;\n  return 302 https://search.dptools.openshift.org$request_uri;\n}\n"
kind: ConfigMap
metadata:
  name: release-controller-ocp-redirect-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: release-controller-ocp-redirect
  name: release-controller-ocp-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      component: release-controller-ocp-redirect
  template:
    metadata:
      labels:
        app: prow
        component: release-controller-ocp-redirect
    spec:
      containers:
        - image: nginxinc/nginx-unprivileged
          name: nginx
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: config
      volumes:
        - configMap:
            name: release-controller-ocp-redirect-config
          name: config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prow
    component: release-controller-ocp-redirect
  name: release-controller-ocp-redirect
spec:
  ports:
  - name: main
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: release-controller-ocp-redirect
  sessionAffinity: None
  type: ClusterIP
