build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: security
  optional: true
  steps:
    env:
      ORG_NAME: openshift-eng
      PROJECT_NAME: art-tools
    workflow: openshift-ci-security
zz_generated_metadata:
  branch: main
  org: openshift-eng
  repo: art-tools
